### 인증이 된 사용자가 선택한 강의에 좋아요 버튼을 누른다.
POST http://localhost:8080/api/lectures/1/likes/toggle
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOlsiVVNFUiJdLCJpYXQiOjE3MjA3MjM4NDksImV4cCI6MTcyMDcyNzQ0OX0.D0atVrXi2ratTGOm4rZUPmYCL4qbBss30HaQRQQW1Go

### 인증이 된 사용자가 선택한 강의에 좋아요를 한다.
POST http://localhost:8080/api/lectures/1/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOlsiVVNFUiJdLCJpYXQiOjE3MjA3MjM4NDksImV4cCI6MTcyMDcyNzQ0OX0.D0atVrXi2ratTGOm4rZUPmYCL4qbBss30HaQRQQW1Go

### 인증이 된 사용자가 선택한 강의에 좋아요 여부 확인한다.
GET http://localhost:8080/api/lectures/1/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOlsiVVNFUiJdLCJpYXQiOjE3MjA3MjM4NDksImV4cCI6MTcyMDcyNzQ0OX0.D0atVrXi2ratTGOm4rZUPmYCL4qbBss30HaQRQQW1Go

### 인증이 된 사용자가 선택한 강의에 좋아요를 취소한다.
DELETE http://localhost:8080/api/lectures/1/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOlsiVVNFUiJdLCJpYXQiOjE3MjA3MjM4NDksImV4cCI6MTcyMDcyNzQ0OX0.D0atVrXi2ratTGOm4rZUPmYCL4qbBss30HaQRQQW1Go