### 회원가입
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "email": "a@example.com",
  "password": "Password1!",
  "gender": "MALE",
  "phoneNumber": "010-0000-0000",
  "address": "판교",
  "role": "USER"
}

### 관리자 로그인
POST http://localhost:8080/api/users/signin
Content-Type: application/json

{
  "email": "d@m",
  "password": "Password1!"
}

### 유저 로그인
POST http://localhost:8080/api/users/signin
Content-Type: application/json

{
"email": "a@m",
"password": "Password1!"
}

### 회원 탈퇴
DELETE http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOlsiVVNFUiJdLCJpYXQiOjE3MjA3NjIzNjIsImV4cCI6MTcyMDc2NTk2Mn0.aiIfBY-x6YM3P5Xk45OJLclUsP1rGM3sbWR6Qf8lAFg