spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;NON_KEYWORDS=DAY,TIME
    driver-class-name: org.h2.Driver
    username: je
    password:

  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  jwt:
    secret: ${JWT_SECRET}
  config:
    activate:
      on-profile: local


  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;NON_KEYWORDS=DAY,TIME
    driver-class-name: org.h2.Driver
    username: je
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
